name: Deploy EC2 with Terraform

on:
  push:
    branches:
      - main # Change to your desired branch

env:
  TF_LOG: TRACE

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Initialize
      run: terraform init

    - name: Terraform Apply
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      run: |
        terraform apply -auto-approve
        echo "instance_public_ip=$(terraform output instance_public_ip)" >> $GITHUB_ENV

